spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://{IP:PORT}/datart?&allowMultiQueries=true
    username: { USERNAME }
    password: { PASSWORD }

  security:
    oauth2:
      enable: true
      client:
        registration:
          cas:
            provider: cas
            client-id: "xxx"
            client-name: "Sign in with xxx"
            client-secret: "xxx"
            authorization-grant-type: authorization_code
            client-authentication-method: post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: userinfo
          qywx:
            provider: qywx
            client-id: "xxxx"
            client-name: "企业微信客户端登录"
            client-secret: "xx"
            authorization-grant-type: authorization_code
            client-authentication-method: post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: snsapi_base
        provider:
          cas:
            authorization-uri: https://cas.xxx.com/cas/oauth2.0/authorize
            token-uri: https://cas.xxx.com/cas/oauth2.0/accessToken
            user-info-uri: https://cas.xxx.com/cas/oauth2.0/profile
            user-name-attribute: id
            userMapping:
              email: "attributes.email"
              name: "attributes.name"
              avatar: "attributes.avatar"
          qywx:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize?appid=xxxxxxxxxxxxxx#wechat_redirect
            token-uri: http://172.17.0.1:23014/oauth2.0/accessToken
            user-info-uri: http://172.17.0.1:23014/oauth2.0/profile
            user-name-attribute: email
            userMapping:
              email: "email"
              name: "name"
              avatar: "thumb_avatar"

# mail config

# mail:
#   host: { 邮箱服务地址 }
#   port: { 端口号 }
#   username: { 邮箱地址 }
#   fromAddress:
#   password: { 邮箱服务密码 }
#   senderName: { 发送者昵称 }
#
#   properties:
#     smtp:
#       starttls:
#         enable: true
#         required: true
#       auth: true
#     mail:
#       smtp:
#         ssl:
#           enable: true


# redis config

#  redis:
#    port: 6379
#    host: { HOST }


server:
  port: { PORT }
  address: { IP }

  # 开启 gzip 压缩，加快请求和响应速度
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*


datart:
  server:
    address: http://{IP/域名}:{端口}

  user:
    active:
      send-mail: true  # 注册用户时是否需要邮件验证激活

  security:
    token:
      secret: "d@a$t%a^r&a*t" #加密密钥
      timeout-min: 30  # 登录会话有效时长，单位：分钟。

  env:
    file-path: ${user.dir}/files # 服务端文件保存位置

  screenshot:
    timeout-seconds: 60
    webdriver-type: CHROME
    webdriver-path: { Web Driver Path }
